[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "node server.js"
  targetPort = 3000
  port = 8889
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
